import { Config } from '../config.js';

export class Preload {
  static resources_manifest_1 = [
    { id: '1', src: `${Config.podURL}/category/shop-by-format/images/background.png` },
    { id: '2', src: `${Config.podURL}/category/shop-by-format/images/care.png` },
    { id: '3', src: `${Config.podURL}/category/shop-by-format/images/cleanse.png` },
    { id: '4', src: `${Config.podURL}/category/shop-by-format/images/protect-and-enchance.png` },
    { id: '5', src: `${Config.podURL}/category/shop-by-format/images/tone-and-prep.png` },
    { id: '6', src: `${Config.podURL}/category/shop-by-format/images/wash.png` },
    { id: '7', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/background.png` },
    {
      id: '8',
      src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/daily-whitening-sun-protect-spf50.png`,
    },
    { id: '9', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/day-cream.png` },
    { id: '10', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/eye-cream.png` },
    { id: '11', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/instabright-glow-up-cream.png` },
    { id: '12', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/instabright-tone-up-cream.png` },
    { id: '13', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/night-cream.png` },
    { id: '14', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/serum-burst-cream.png` },
    { id: '15', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/super-cream-oily-skin.png` },
    { id: '16', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/super-cream.png` },
    { id: '17', src: `${Config.podURL}/category/shop-by-format/subcategory/care/images/whip-day-cream.png` },
    {
      id: '18',
      src: `${Config.podURL}/category/shop-by-format/subcategory/cleanse/images/anti-bacterial-facial-wipes.png`,
    },
    {
      id: '19',
      src: `${Config.podURL}/category/shop-by-format/subcategory/cleanse/images/anti-bacterial-protection-facial-mist.png`,
    },
    { id: '20', src: `${Config.podURL}/category/shop-by-format/subcategory/cleanse/images/background.png` },
    { id: '21', src: `${Config.podURL}/category/shop-by-format/subcategory/cleanse/images/cleansing-balm.png` },
    { id: '22', src: `${Config.podURL}/category/shop-by-format/subcategory/cleanse/images/vitamin-micellar-water.png` },
    {
      id: '23',
      src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/anti-ageing-expert-bb-cream-beige.png`,
    },
    {
      id: '24',
      src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/anti-ageing-expert-bb-cream-light.png`,
    },
    { id: '25', src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/background.png` },
    {
      id: '26',
      src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/bb-cc-cream-beige.png`,
    },
    {
      id: '27',
      src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/bb-cc-cream-light.png`,
    },
    {
      id: '28',
      src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/bb-magic-powder.png`,
    },
    {
      id: '29',
      src: `${Config.podURL}/category/shop-by-format/subcategory/protect-and-enhance/images/instabright-tone-up-milk-powder.png`,
    },
    { id: '30', src: `${Config.podURL}/category/shop-by-format/subcategory/tone-and-prep/images/background.png` },
    {
      id: '31',
      src: `${Config.podURL}/category/shop-by-format/subcategory/tone-and-prep/images/double-action-serum.png`,
    },
    {
      id: '32',
      src: `${Config.podURL}/category/shop-by-format/subcategory/tone-and-prep/images/instabright-tone-up-essence.png`,
    },
    {
      id: '33',
      src: `${Config.podURL}/category/shop-by-format/subcategory/tone-and-prep/images/serum-burst-cream.png`,
    },
    {
      id: '34',
      src: `${Config.podURL}/category/shop-by-format/subcategory/tone-and-prep/images/ultimate-youth-essence.png`,
    },
    { id: '35', src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/acne-clear-facial-foam.png` },
    {
      id: '36',
      src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/anti-bacterial-facial-foam.png`,
    },
    { id: '37', src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/background.png` },
    {
      id: '38',
      src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/mineral-clay-clear-solutions.png`,
    },
    { id: '39', src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/mineral-clay-pure-white.png` },
    { id: '40', src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/mineral-clay-white-beauty.png` },
    { id: '41', src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/pure-white-facial-foam.png` },
    { id: '42', src: `${Config.podURL}/category/shop-by-format/subcategory/wash/images/white-beauty-facial-foam.png` },
    { id: '43', src: `${Config.podURL}/category/shop-by-need/images/acne-and-oil-control.png` },
    { id: '44', src: `${Config.podURL}/category/shop-by-need/images/background.png` },
    { id: '45', src: `${Config.podURL}/category/shop-by-need/images/bright-glow.png` },
    { id: '46', src: `${Config.podURL}/category/shop-by-need/images/spotless-and-even-tone.png` },
    { id: '47', src: `${Config.podURL}/category/shop-by-need/images/youthful-glow.png` },
    {
      id: '48',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/acne-clear-facial-foam.png`,
    },
    {
      id: '49',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/anti-bacterial-facial-foam.png`,
    },
    {
      id: '50',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/anti-bacterial-facial-wipes.png`,
    },
    {
      id: '51',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/anti-bacterial-protection-facial-mist.png`,
    },
    { id: '52', src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/background.png` },
    {
      id: '53',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/mineral-clay-clear-solutions.png`,
    },
    {
      id: '54',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/mineral-clay-pure-white.png`,
    },
    {
      id: '55',
      src: `${Config.podURL}/category/shop-by-need/subcategory/acne-and-oil-control/images/pure-white-facial-foam.png`,
    },
    { id: '56', src: `${Config.podURL}/category/shop-by-need/subcategory/bright-glow/images/background.png` },
    { id: '57', src: `${Config.podURL}/category/shop-by-need/subcategory/bright-glow/images/cleansing-balm.png` },
    {
      id: '58',
      src: `${Config.podURL}/category/shop-by-need/subcategory/bright-glow/images/instabright-glow-up-cream.png`,
    },
    { id: '59', src: `${Config.podURL}/category/shop-by-need/subcategory/bright-glow/images/serum-burst-cream.png` },
    {
      id: '60',
      src: `${Config.podURL}/category/shop-by-need/subcategory/bright-glow/images/serum-burst-potion-essence.png`,
    },
    {
      id: '61',
      src: `${Config.podURL}/category/shop-by-need/subcategory/bright-glow/images/vitamin-micellar-water.png`,
    },
    {
      id: '62',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/background.png`,
    },
    {
      id: '63',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/bb-cc-cream.png`,
    },
    {
      id: '64',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/bb-magic-powder.png`,
    },
    {
      id: '65',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/daily-whitening-sun-protect-spf50.png`,
    },
    {
      id: '66',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/instabright-tone-up-cream.png`,
    },
    {
      id: '67',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/instabright-tone-up-essence.png`,
    },
    {
      id: '68',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/instabright-tone-up-milk-powder.png`,
    },
    {
      id: '69',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/mineral-clay-white-beauty.png`,
    },
    {
      id: '70',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/super-cream-oily-skin.png`,
    },
    {
      id: '71',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/super-cream.png`,
    },
    {
      id: '72',
      src: `${Config.podURL}/category/shop-by-need/subcategory/spotless-and-even-tone/images/white-beauty-facial-foam.png`,
    },
    {
      id: '73',
      src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/anti-ageing-expert-bb-cream.png`,
    },
    { id: '74', src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/background.png` },
    { id: '75', src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/day-cream.png` },
    {
      id: '76',
      src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/double-action-serum.png`,
    },
    { id: '77', src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/eye-cream.png` },
    { id: '78', src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/night-cream.png` },
    {
      id: '80',
      src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/ultimate-youth-essence.png`,
    },
    { id: '81', src: `${Config.podURL}/category/shop-by-need/subcategory/youthful-glow/images/whip-day-cream.png` },
    { id: '82', src: `${Config.podURL}/category/shop-by-range/images/anti-maskne.png` },
    { id: '83', src: `${Config.podURL}/category/shop-by-range/images/background.png` },
    { id: '84', src: `${Config.podURL}/category/shop-by-range/images/bright-now.png` },
    { id: '85', src: `${Config.podURL}/category/shop-by-range/images/cleanse-as-you-glow.png` },
    { id: '86', src: `${Config.podURL}/category/shop-by-range/images/dewy-skin-goals.png` },
    { id: '87', src: `${Config.podURL}/category/shop-by-range/images/glow-your-own-way.png` },
    { id: '88', src: `${Config.podURL}/category/shop-by-range/images/hello-glow.png` },
    { id: '89', src: `${Config.podURL}/category/shop-by-range/images/lets-clay.png` },
    { id: '90', src: `${Config.podURL}/category/shop-by-range/images/perfect-bare-skin-look.png` },
    { id: '91', src: `${Config.podURL}/category/shop-by-range/images/you-do-youth.png` },
    { id: '92', src: `${Config.podURL}/category/shop-by-range/subcategory/anti-maskne/images/background.png` },
    { id: '93', src: `${Config.podURL}/category/shop-by-range/subcategory/anti-maskne/images/products.png` },
    { id: '94', src: `${Config.podURL}/category/shop-by-range/subcategory/bright-now/images/background.png` },
    { id: '95', src: `${Config.podURL}/category/shop-by-range/subcategory/bright-now/images/products.png` },
    { id: '96', src: `${Config.podURL}/category/shop-by-range/subcategory/cleanse-as-you-glow/images/background.png` },
    { id: '97', src: `${Config.podURL}/category/shop-by-range/subcategory/cleanse-as-you-glow/images/products.png` },
    { id: '98', src: `${Config.podURL}/category/shop-by-range/subcategory/dewy-skin-goals/images/background.png` },
    { id: '99', src: `${Config.podURL}/category/shop-by-range/subcategory/dewy-skin-goals/images/products.png` },
    { id: '100', src: `${Config.podURL}/category/shop-by-range/subcategory/glow-your-own-way/images/background.png` },
    { id: '101', src: `${Config.podURL}/category/shop-by-range/subcategory/glow-your-own-way/images/products.png` },
    { id: '102', src: `${Config.podURL}/category/shop-by-range/subcategory/hello-glow/images/background.png` },
    { id: '103', src: `${Config.podURL}/category/shop-by-range/subcategory/hello-glow/images/products.png` },
    { id: '104', src: `${Config.podURL}/category/shop-by-range/subcategory/lets-clay/images/background.png` },
    { id: '105', src: `${Config.podURL}/category/shop-by-range/subcategory/lets-clay/images/products.png` },
    {
      id: '106',
      src: `${Config.podURL}/category/shop-by-range/subcategory/perfect-bare-skin-look/images/background.png`,
    },
    {
      id: '107',
      src: `${Config.podURL}/category/shop-by-range/subcategory/perfect-bare-skin-look/images/products.png`,
    },
    { id: '108', src: `${Config.podURL}/category/shop-by-range/subcategory/you-do-youth/images/background.png` },
    { id: '109', src: `${Config.podURL}/category/shop-by-range/subcategory/you-do-youth/images/products.png` },
    { id: '110', src: `${Config.podURL}/category/whats-new/images/background.png` },
    { id: '111', src: `${Config.podURL}/category/whats-new/images/products.png` },
    { id: '112', src: `${Config.podURL}/category/whats-trending/images/background.png` },
    { id: '113', src: `${Config.podURL}/category/whats-trending/images/products.png` },
    { id: '114', src: `${Config.podURL}/product/acne-clear-facial-foam/images/product-name.png` },
    {
      id: '115',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/about-the-product-section/images/background.png`,
    },
    {
      id: '116',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/about-the-product-section/images/info-01.png`,
    },
    {
      id: '117',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/about-the-product-section/images/product-shot.png`,
    },
    {
      id: '118',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/goes-well-with-section/images/background.png`,
    },
    {
      id: '119',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/goes-well-with-section/images/product-shot-01.png`,
    },
    {
      id: '120',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/goes-well-with-section/images/product-shot-02.png`,
    },
    {
      id: '121',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/goes-well-with-section/images/product-shot-03.png`,
    },
    { id: '122', src: `${Config.podURL}/product/acne-clear-facial-foam/resources/home-section/images/background.png` },
    {
      id: '123',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/home-section/images/product-shot.png`,
    },
    {
      id: '124',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/how-to-use-section/images/background.png`,
    },
    {
      id: '125',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/how-to-use-section/images/info-01.png`,
    },
    {
      id: '126',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/how-to-use-section/images/info-02.png`,
    },
    {
      id: '127',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/how-to-use-section/images/info-03.png`,
    },
    {
      id: '128',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/how-to-use-section/images/product-shot.png`,
    },
    { id: '129', src: `${Config.podURL}/product/acne-clear-facial-foam/resources/images/ponds-logo.png` },
    { id: '130', src: `${Config.podURL}/product/acne-clear-facial-foam/resources/images/product-name.png` },
    {
      id: '131',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/key-ingredients-section/images/background.png`,
    },
    {
      id: '132',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/key-ingredients-section/images/info-01.png`,
    },
    {
      id: '133',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/key-ingredients-section/images/info-02.png`,
    },
    {
      id: '134',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/key-ingredients-section/images/product-shot.png`,
    },
    {
      id: '135',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/ratings-and-reviews-section/images/background.png`,
    },
    {
      id: '136',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/ratings-and-reviews-section/images/info-01.png`,
    },
    {
      id: '137',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/ratings-and-reviews-section/images/info-02.png`,
    },
    {
      id: '138',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/ratings-and-reviews-section/images/info-03.png`,
    },
    {
      id: '139',
      src: `${Config.podURL}/product/acne-clear-facial-foam/resources/ratings-and-reviews-section/images/product-shot.png`,
    },
    { id: '140', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/product-name.png` },
    { id: '141', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/product-name.png` },
    { id: '142', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/product-name.png` },
    { id: '143', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/product-name.png` },
    { id: '144', src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/product-name.png` },
    { id: '145', src: `${Config.podURL}/product/bb-cc-cream/images/product-name.png` },
    { id: '146', src: `${Config.podURL}/product/bb-magic-powder/images/product-name.png` },
    { id: '147', src: `${Config.podURL}/product/cleansing-balm/images/product-name.png` },
    { id: '148', src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/product-name.png` },
    { id: '149', src: `${Config.podURL}/product/day-cream/images/product-name.png` },
    { id: '150', src: `${Config.podURL}/product/double-action-serum/images/product-name.png` },
    { id: '151', src: `${Config.podURL}/product/eye-cream/images/product-name.png` },
    { id: '152', src: `${Config.podURL}/product/instabright-glow-up-cream/images/product-name.png` },
    { id: '153', src: `${Config.podURL}/product/instabright-tone-up-cream/images/product-name.png` },
    { id: '154', src: `${Config.podURL}/product/instabright-tone-up-essence/images/product-name.png` },
    { id: '155', src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/product-name.png` },
    { id: '156', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/product-name.png` },
    { id: '157', src: `${Config.podURL}/product/mineral-clay-pure-white/images/product-name.png` },
    { id: '158', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/product-name.png` },
    { id: '159', src: `${Config.podURL}/product/night-cream/images/product-name.png` },
    { id: '160', src: `${Config.podURL}/product/pure-white-facial-foam/images/product-name.png` },
    { id: '161', src: `${Config.podURL}/product/serum-burst-cream/images/product-name.png` },
    { id: '162', src: `${Config.podURL}/product/serum-burst-potion-essence/images/product-name.png` },
    { id: '163', src: `${Config.podURL}/product/super-cream/images/product-name.png` },
    { id: '164', src: `${Config.podURL}/product/super-cream-detox/images/product-name.png` },
    { id: '165', src: `${Config.podURL}/product/ultimate-youth-essence/images/product-name.png` },
    { id: '166', src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/product-name.png` },
    { id: '167', src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/product-name.png` },
    { id: '168', src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/product-name.png` },
    { id: '169', src: `${Config.podURL}/product/whip-day-cream/images/product-name.png` },
    { id: '170', src: `${Config.podURL}/product/white-beauty-facial-foam/images/product-name.png` },
    { id: '171', src: `${Config.podURL}/resources/images/common/age-miracle-theme/about-the-product.png` },
    { id: '172', src: `${Config.podURL}/resources/images/common/age-miracle-theme/goes-well-with.png` },
    { id: '173', src: `${Config.podURL}/resources/images/common/age-miracle-theme/how-to-use.png` },
    { id: '174', src: `${Config.podURL}/resources/images/common/age-miracle-theme/key-ingredients.png` },
    { id: '175', src: `${Config.podURL}/resources/images/common/age-miracle-theme/ponds-logo.png` },
    { id: '176', src: `${Config.podURL}/resources/images/common/age-miracle-theme/ratings-and-reviews.png` },
    { id: '177', src: `${Config.podURL}/resources/images/common/back-to-home.png` },
    { id: '178', src: `${Config.podURL}/resources/images/common/back.png` },
    { id: '179', src: `${Config.podURL}/resources/images/common/ponds-loading.png` },
    { id: '180', src: `${Config.podURL}/resources/images/common/ponds-logo.png` },
    { id: '181', src: `${Config.podURL}/resources/images/common/white-beauty-pink-theme/about-the-product.png` },
    { id: '182', src: `${Config.podURL}/resources/images/common/white-beauty-pink-theme/goes-well-with.png` },
    { id: '183', src: `${Config.podURL}/resources/images/common/white-beauty-pink-theme/how-to-use.png` },
    { id: '184', src: `${Config.podURL}/resources/images/common/white-beauty-pink-theme/key-ingredients.png` },
    { id: '185', src: `${Config.podURL}/resources/images/common/white-beauty-pink-theme/ponds-logo.png` },
    { id: '186', src: `${Config.podURL}/resources/images/common/white-beauty-pink-theme/ratings-and-reviews.png` },
    { id: '187', src: `${Config.podURL}/resources/images/common/white-beauty-white-theme/about-the-product.png` },
    { id: '188', src: `${Config.podURL}/resources/images/common/white-beauty-white-theme/goes-well-with.png` },
    { id: '189', src: `${Config.podURL}/resources/images/common/white-beauty-white-theme/how-to-use.png` },
    { id: '190', src: `${Config.podURL}/resources/images/common/white-beauty-white-theme/key-ingredients.png` },
    { id: '191', src: `${Config.podURL}/resources/images/common/white-beauty-white-theme/ponds-logo.png` },
    { id: '192', src: `${Config.podURL}/resources/images/common/white-beauty-white-theme/ratings-and-reviews.png` },
    { id: '193', src: `${Config.podURL}/resources/menu/shop-by-format.png` },
    { id: '194', src: `${Config.podURL}/resources/menu/shop-by-need.png` },
    { id: '195', src: `${Config.podURL}/resources/menu/shop-by-range.png` },
    { id: '196', src: `${Config.podURL}/resources/menu/trending.png` },
    { id: '197', src: `${Config.podURL}/resources/menu/whats-new.png` },
    { id: '198', src: `${Config.podURL}/resources/images/home.jpg` },
    { id: '199', src: `${Config.podURL}/resources/menu/menu.jpg` },
  ];

  static resources_manifest_2 = [
    { id: '1', src: `${Config.podURL}/product/acne-clear-facial-foam/images/about-the-product-section.jpg` },
    { id: '2', src: `${Config.podURL}/product/acne-clear-facial-foam/images/goes-well-with-section.jpg` },
    { id: '3', src: `${Config.podURL}/product/acne-clear-facial-foam/images/home-section.jpg` },
    { id: '4', src: `${Config.podURL}/product/acne-clear-facial-foam/images/how-to-use-section.jpg` },
    { id: '5', src: `${Config.podURL}/product/acne-clear-facial-foam/images/key-ingredients-section.jpg` },
    { id: '6', src: `${Config.podURL}/product/acne-clear-facial-foam/images/ratings-and-reviews-section.jpg` },
    { id: '7', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/about-the-product-section.jpg` },
    { id: '8', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/goes-well-with-section.jpg` },
    { id: '9', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/home-section.jpg` },
    { id: '10', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/how-to-use-section.jpg` },
    { id: '11', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/key-ingredients-section.jpg` },
    { id: '12', src: `${Config.podURL}/product/anti-ageing-expert-bb-cream/images/ratings-and-reviews-section.jpg` },
    { id: '13', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/about-the-product-section.jpg` },
    { id: '14', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/goes-well-with-section.jpg` },
    { id: '15', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/home-section.jpg` },
    { id: '16', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/how-to-use-section.jpg` },
    { id: '17', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/key-ingredients-section.jpg` },
    { id: '18', src: `${Config.podURL}/product/anti-bacterial-cleansing-wipes/images/ratings-and-reviews-section.jpg` },
    { id: '19', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/about-the-product-section.jpg` },
    { id: '20', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/goes-well-with-section.jpg` },
    { id: '21', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/home-section.jpg` },
    { id: '22', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/how-to-use-section.jpg` },
    { id: '23', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/key-ingredients-section.jpg` },
    { id: '24', src: `${Config.podURL}/product/anti-bacterial-facial-foam/images/ratings-and-reviews-section.jpg` },
    { id: '25', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/about-the-product-section.jpg` },
    { id: '26', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/goes-well-with-section.jpg` },
    { id: '27', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/home-section.jpg` },
    { id: '28', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/how-to-use-section.jpg` },
    { id: '29', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/key-ingredients-section.jpg` },
    { id: '30', src: `${Config.podURL}/product/anti-bacterial-facial-scrub/images/ratings-and-reviews-section.jpg` },
    {
      id: '31',
      src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/about-the-product-section.jpg`,
    },
    {
      id: '32',
      src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/goes-well-with-section.jpg`,
    },
    { id: '33', src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/home-section.jpg` },
    { id: '34', src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/how-to-use-section.jpg` },
    {
      id: '35',
      src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/key-ingredients-section.jpg`,
    },
    {
      id: '36',
      src: `${Config.podURL}/product/anti-bacterial-protection-facial-mist/images/ratings-and-reviews-section.jpg`,
    },
    { id: '37', src: `${Config.podURL}/product/bb-cc-cream/images/about-the-product-section.jpg` },
    { id: '38', src: `${Config.podURL}/product/bb-cc-cream/images/goes-well-with-section.jpg` },
    { id: '39', src: `${Config.podURL}/product/bb-cc-cream/images/home-section.jpg` },
    { id: '40', src: `${Config.podURL}/product/bb-cc-cream/images/how-to-use-section.jpg` },
    { id: '41', src: `${Config.podURL}/product/bb-cc-cream/images/key-ingredients-section.jpg` },
    { id: '42', src: `${Config.podURL}/product/bb-cc-cream/images/ratings-and-reviews-section.jpg` },
    { id: '43', src: `${Config.podURL}/product/bb-magic-powder/images/about-the-product-section.jpg` },
    { id: '44', src: `${Config.podURL}/product/bb-magic-powder/images/goes-well-with-section.jpg` },
    { id: '45', src: `${Config.podURL}/product/bb-magic-powder/images/home-section.jpg` },
    { id: '46', src: `${Config.podURL}/product/bb-magic-powder/images/how-to-use-section.jpg` },
    { id: '47', src: `${Config.podURL}/product/bb-magic-powder/images/key-ingredients-section.jpg` },
    { id: '48', src: `${Config.podURL}/product/bb-magic-powder/images/ratings-and-reviews-section.jpg` },
    { id: '49', src: `${Config.podURL}/product/cleansing-balm/images/about-the-product-section.jpg` },
    { id: '50', src: `${Config.podURL}/product/cleansing-balm/images/goes-well-with-section.jpg` },
    { id: '51', src: `${Config.podURL}/product/cleansing-balm/images/home-section.jpg` },
    { id: '52', src: `${Config.podURL}/product/cleansing-balm/images/how-to-use-section.jpg` },
    { id: '53', src: `${Config.podURL}/product/cleansing-balm/images/key-ingredients-section.jpg` },
    { id: '54', src: `${Config.podURL}/product/cleansing-balm/images/ratings-and-reviews-section.jpg` },
    {
      id: '55',
      src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/about-the-product-section.jpg`,
    },
    { id: '56', src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/goes-well-with-section.jpg` },
    { id: '57', src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/home-section.jpg` },
    { id: '58', src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/how-to-use-section.jpg` },
    { id: '59', src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/key-ingredients-section.jpg` },
    {
      id: '60',
      src: `${Config.podURL}/product/daily-whitening-sun-protect-spf50/images/ratings-and-reviews-section.jpg`,
    },
    { id: '61', src: `${Config.podURL}/product/day-cream/images/about-the-product-section.jpg` },
    { id: '62', src: `${Config.podURL}/product/day-cream/images/goes-well-with-section.jpg` },
    { id: '63', src: `${Config.podURL}/product/day-cream/images/home-section.jpg` },
    { id: '64', src: `${Config.podURL}/product/day-cream/images/how-to-use-section.jpg` },
    { id: '65', src: `${Config.podURL}/product/day-cream/images/key-ingredients-section.jpg` },
    { id: '66', src: `${Config.podURL}/product/day-cream/images/ratings-and-reviews-section.jpg` },
    { id: '67', src: `${Config.podURL}/product/double-action-serum/images/about-the-product-section.jpg` },
    { id: '68', src: `${Config.podURL}/product/double-action-serum/images/goes-well-with-section.jpg` },
    { id: '69', src: `${Config.podURL}/product/double-action-serum/images/home-section.jpg` },
    { id: '70', src: `${Config.podURL}/product/double-action-serum/images/how-to-use-section.jpg` },
    { id: '71', src: `${Config.podURL}/product/double-action-serum/images/key-ingredients-section.jpg` },
    { id: '72', src: `${Config.podURL}/product/double-action-serum/images/ratings-and-reviews-section.jpg` },
    { id: '73', src: `${Config.podURL}/product/eye-cream/images/about-the-product-section.jpg` },
    { id: '74', src: `${Config.podURL}/product/eye-cream/images/goes-well-with-section.jpg` },
    { id: '75', src: `${Config.podURL}/product/eye-cream/images/home-section.jpg` },
    { id: '76', src: `${Config.podURL}/product/eye-cream/images/how-to-use-section.jpg` },
    { id: '77', src: `${Config.podURL}/product/eye-cream/images/key-ingredients-section.jpg` },
    { id: '78', src: `${Config.podURL}/product/eye-cream/images/ratings-and-reviews-section.jpg` },
    { id: '79', src: `${Config.podURL}/product/instabright-glow-up-cream/images/about-the-product-section.jpg` },
    { id: '80', src: `${Config.podURL}/product/instabright-glow-up-cream/images/goes-well-with-section.jpg` },
    { id: '81', src: `${Config.podURL}/product/instabright-glow-up-cream/images/home-section.jpg` },
    { id: '82', src: `${Config.podURL}/product/instabright-glow-up-cream/images/how-to-use-section.jpg` },
    { id: '83', src: `${Config.podURL}/product/instabright-glow-up-cream/images/key-ingredients-section.jpg` },
    { id: '84', src: `${Config.podURL}/product/instabright-glow-up-cream/images/ratings-and-reviews-section.jpg` },
    { id: '85', src: `${Config.podURL}/product/instabright-tone-up-cream/images/about-the-product-section.jpg` },
    { id: '86', src: `${Config.podURL}/product/instabright-tone-up-cream/images/goes-well-with-section.jpg` },
    { id: '87', src: `${Config.podURL}/product/instabright-tone-up-cream/images/home-section.jpg` },
    { id: '88', src: `${Config.podURL}/product/instabright-tone-up-cream/images/how-to-use-section.jpg` },
    { id: '89', src: `${Config.podURL}/product/instabright-tone-up-cream/images/key-ingredients-section.jpg` },
    { id: '90', src: `${Config.podURL}/product/instabright-tone-up-cream/images/ratings-and-reviews-section.jpg` },
    { id: '91', src: `${Config.podURL}/product/instabright-tone-up-essence/images/about-the-product-section.jpg` },
    { id: '92', src: `${Config.podURL}/product/instabright-tone-up-essence/images/goes-well-with-section.jpg` },
    { id: '93', src: `${Config.podURL}/product/instabright-tone-up-essence/images/home-section.jpg` },
    { id: '94', src: `${Config.podURL}/product/instabright-tone-up-essence/images/how-to-use-section.jpg` },
    { id: '95', src: `${Config.podURL}/product/instabright-tone-up-essence/images/key-ingredients-section.jpg` },
    { id: '96', src: `${Config.podURL}/product/instabright-tone-up-essence/images/ratings-and-reviews-section.jpg` },
    { id: '97', src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/about-the-product-section.jpg` },
    { id: '98', src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/goes-well-with-section.jpg` },
    { id: '99', src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/home-section.jpg` },
    { id: '100', src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/how-to-use-section.jpg` },
    { id: '101', src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/key-ingredients-section.jpg` },
    {
      id: '102',
      src: `${Config.podURL}/product/instabright-tone-up-milk-powder/images/ratings-and-reviews-section.jpg`,
    },
    { id: '103', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/about-the-product-section.jpg` },
    { id: '104', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/goes-well-with-section.jpg` },
    { id: '105', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/home-section.jpg` },
    { id: '106', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/how-to-use-section.jpg` },
    { id: '107', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/key-ingredients-section.jpg` },
    { id: '108', src: `${Config.podURL}/product/mineral-clay-clear-solutions/images/ratings-and-reviews-section.jpg` },
    { id: '109', src: `${Config.podURL}/product/mineral-clay-pure-white/images/about-the-product-section.jpg` },
    { id: '110', src: `${Config.podURL}/product/mineral-clay-pure-white/images/goes-well-with-section.jpg` },
    { id: '111', src: `${Config.podURL}/product/mineral-clay-pure-white/images/home-section.jpg` },
    { id: '112', src: `${Config.podURL}/product/mineral-clay-pure-white/images/how-to-use-section.jpg` },
    { id: '113', src: `${Config.podURL}/product/mineral-clay-pure-white/images/key-ingredients-section.jpg` },
    { id: '114', src: `${Config.podURL}/product/mineral-clay-pure-white/images/ratings-and-reviews-section.jpg` },
    { id: '115', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/about-the-product-section.jpg` },
    { id: '116', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/goes-well-with-section.jpg` },
    { id: '117', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/home-section.jpg` },
    { id: '118', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/how-to-use-section.jpg` },
    { id: '119', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/key-ingredients-section.jpg` },
    { id: '120', src: `${Config.podURL}/product/mineral-clay-white-beauty/images/ratings-and-reviews-section.jpg` },
    { id: '121', src: `${Config.podURL}/product/night-cream/images/about-the-product-section.jpg` },
    { id: '122', src: `${Config.podURL}/product/night-cream/images/goes-well-with-section.jpg` },
    { id: '123', src: `${Config.podURL}/product/night-cream/images/home-section.jpg` },
    { id: '124', src: `${Config.podURL}/product/night-cream/images/how-to-use-section.jpg` },
    { id: '125', src: `${Config.podURL}/product/night-cream/images/key-ingredients-section.jpg` },
    { id: '126', src: `${Config.podURL}/product/night-cream/images/ratings-and-reviews-section.jpg` },
    { id: '127', src: `${Config.podURL}/product/pure-white-facial-foam/images/about-the-product-section.jpg` },
    { id: '128', src: `${Config.podURL}/product/pure-white-facial-foam/images/goes-well-with-section.jpg` },
    { id: '129', src: `${Config.podURL}/product/pure-white-facial-foam/images/home-section.jpg` },
    { id: '130', src: `${Config.podURL}/product/pure-white-facial-foam/images/how-to-use-section.jpg` },
    { id: '131', src: `${Config.podURL}/product/pure-white-facial-foam/images/key-ingredients-section.jpg` },
    { id: '132', src: `${Config.podURL}/product/pure-white-facial-foam/images/ratings-and-reviews-section.jpg` },
    { id: '133', src: `${Config.podURL}/product/serum-burst-cream/images/about-the-product-section.jpg` },
    { id: '134', src: `${Config.podURL}/product/serum-burst-cream/images/goes-well-with-section.jpg` },
    { id: '135', src: `${Config.podURL}/product/serum-burst-cream/images/home-section.jpg` },
    { id: '136', src: `${Config.podURL}/product/serum-burst-cream/images/how-to-use-section.jpg` },
    { id: '137', src: `${Config.podURL}/product/serum-burst-cream/images/key-ingredients-section.jpg` },
    { id: '138', src: `${Config.podURL}/product/serum-burst-cream/images/ratings-and-reviews-section.jpg` },
    { id: '139', src: `${Config.podURL}/product/serum-burst-potion-essence/images/about-the-product-section.jpg` },
    { id: '140', src: `${Config.podURL}/product/serum-burst-potion-essence/images/goes-well-with-section.jpg` },
    { id: '141', src: `${Config.podURL}/product/serum-burst-potion-essence/images/home-section.jpg` },
    { id: '142', src: `${Config.podURL}/product/serum-burst-potion-essence/images/how-to-use-section.jpg` },
    { id: '143', src: `${Config.podURL}/product/serum-burst-potion-essence/images/key-ingredients-section.jpg` },
    { id: '144', src: `${Config.podURL}/product/serum-burst-potion-essence/images/ratings-and-reviews-section.jpg` },
    { id: '145', src: `${Config.podURL}/product/super-cream/images/about-the-product-section.jpg` },
    { id: '146', src: `${Config.podURL}/product/super-cream/images/goes-well-with-section.jpg` },
    { id: '147', src: `${Config.podURL}/product/super-cream/images/home-section.jpg` },
    { id: '148', src: `${Config.podURL}/product/super-cream/images/how-to-use-section.jpg` },
    { id: '149', src: `${Config.podURL}/product/super-cream/images/key-ingredients-section.jpg` },
    { id: '150', src: `${Config.podURL}/product/super-cream/images/ratings-and-reviews-section.jpg` },
    { id: '151', src: `${Config.podURL}/product/super-cream-detox/images/about-the-product-section.jpg` },
    { id: '152', src: `${Config.podURL}/product/super-cream-detox/images/goes-well-with-section.jpg` },
    { id: '153', src: `${Config.podURL}/product/super-cream-detox/images/home-section.jpg` },
    { id: '154', src: `${Config.podURL}/product/super-cream-detox/images/how-to-use-section.jpg` },
    { id: '155', src: `${Config.podURL}/product/super-cream-detox/images/key-ingredients-section.jpg` },
    { id: '156', src: `${Config.podURL}/product/super-cream-detox/images/ratings-and-reviews-section.jpg` },
    { id: '157', src: `${Config.podURL}/product/ultimate-youth-essence/images/about-the-product-section.jpg` },
    { id: '158', src: `${Config.podURL}/product/ultimate-youth-essence/images/goes-well-with-section.jpg` },
    { id: '159', src: `${Config.podURL}/product/ultimate-youth-essence/images/home-section.jpg` },
    { id: '160', src: `${Config.podURL}/product/ultimate-youth-essence/images/how-to-use-section.jpg` },
    { id: '161', src: `${Config.podURL}/product/ultimate-youth-essence/images/key-ingredients-section.jpg` },
    { id: '162', src: `${Config.podURL}/product/ultimate-youth-essence/images/ratings-and-reviews-section.jpg` },
    {
      id: '163',
      src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/about-the-product-section.jpg`,
    },
    {
      id: '164',
      src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/goes-well-with-section.jpg`,
    },
    { id: '165', src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/home-section.jpg` },
    {
      id: '166',
      src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/how-to-use-section.jpg`,
    },
    {
      id: '167',
      src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/key-ingredients-section.jpg`,
    },
    {
      id: '168',
      src: `${Config.podURL}/product/vitamin-micellar-water-brightening-rose/images/ratings-and-reviews-section.jpg`,
    },
    {
      id: '169',
      src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/about-the-product-section.jpg`,
    },
    {
      id: '170',
      src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/goes-well-with-section.jpg`,
    },
    { id: '171', src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/home-section.jpg` },
    {
      id: '172',
      src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/how-to-use-section.jpg`,
    },
    {
      id: '173',
      src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/key-ingredients-section.jpg`,
    },
    {
      id: '174',
      src: `${Config.podURL}/product/vitamin-micellar-water-detoxing-charcoal/images/ratings-and-reviews-section.jpg`,
    },
    {
      id: '175',
      src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/about-the-product-section.jpg`,
    },
    {
      id: '176',
      src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/goes-well-with-section.jpg`,
    },
    { id: '177', src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/home-section.jpg` },
    { id: '178', src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/how-to-use-section.jpg` },
    {
      id: '179',
      src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/key-ingredients-section.jpg`,
    },
    {
      id: '180',
      src: `${Config.podURL}/product/vitamin-micellar-water-nourishing-milk/images/ratings-and-reviews-section.jpg`,
    },
    { id: '181', src: `${Config.podURL}/product/whip-day-cream/images/about-the-product-section.jpg` },
    { id: '182', src: `${Config.podURL}/product/whip-day-cream/images/goes-well-with-section.jpg` },
    { id: '183', src: `${Config.podURL}/product/whip-day-cream/images/home-section.jpg` },
    { id: '184', src: `${Config.podURL}/product/whip-day-cream/images/how-to-use-section.jpg` },
    { id: '185', src: `${Config.podURL}/product/whip-day-cream/images/key-ingredients-section.jpg` },
    { id: '186', src: `${Config.podURL}/product/whip-day-cream/images/ratings-and-reviews-section.jpg` },
    { id: '187', src: `${Config.podURL}/product/white-beauty-facial-foam/images/about-the-product-section.jpg` },
    { id: '188', src: `${Config.podURL}/product/white-beauty-facial-foam/images/goes-well-with-section.jpg` },
    { id: '189', src: `${Config.podURL}/product/white-beauty-facial-foam/images/home-section.jpg` },
    { id: '190', src: `${Config.podURL}/product/white-beauty-facial-foam/images/how-to-use-section.jpg` },
    { id: '191', src: `${Config.podURL}/product/white-beauty-facial-foam/images/key-ingredients-section.jpg` },
    { id: '192', src: `${Config.podURL}/product/white-beauty-facial-foam/images/ratings-and-reviews-section.jpg` },
  ];

  // static load(onComplete, onProgress) {
  //   console.log('loading...');
  //   var queue1 = new createjs.LoadQueue();

  //   queue1.on('complete', () => {
  //     onComplete();
  //     var queue2 = new createjs.LoadQueue();
  //     queue2.on('complete', () => console.log('next batch preload done'));
  //     queue2.loadManifest(Preload.resources_manifest_2);
  //   });
  //   queue1.on('progress', (event) => onProgress(event.loaded));

  //   queue1.loadManifest(Preload.resources_manifest_1);
  // }

  static load(onComplete, onProgress) {
    console.log('loading...');

    var queue2 = new createjs.LoadQueue();
    queue2.on('complete', () => {
      console.log('load complete');
      onComplete();
    });
    queue2.loadManifest(Preload.resources_manifest_2);
  }
}
